### ISSUE TITLE
/api/oauth/userinfo is trying to access request.headers, which prevents it from being rendered statically.

### ISSUE THREAD

**Issue by kodaneflash** [dubinc/dub#1181]
Received this error on deployment - web:build: API error occurred Dynamic server usage: Route /api/oauth/userinfo couldn't be rendered statically because it accessed `request.headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
web:build:    Generating static pages (60/80) 
    at nnr (/var/task/sandbox.js:392:17058)
    at /var/task/sandbox.js:392:15715
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/sandbox.js:392:14472 {
  hideStackTrace: true,
  code: 'NOW_SANDBOX_WORKER_MAX_MIDDLEWARE_SIZE',
  link: 'https://vercel.link/edge-function-size',
  action: 'Learn More'

**Comment by dor123official** [comment]
me too have same problem

**Comment by steven-tey** [comment]
Does this block the build?

**Comment by Husky-Devel** [comment]
I seem to be having this same issue but on /api/analytics/dashboard 
![image](https://github.com/user-attachments/assets/ca2a0a0a-4a13-46f5-aaf1-aeab567d0b6c)

The build failes because of it i also get NOW_SANDBOX_WORKER_MAX_MIDDLEWARE_SIZE error as seen in this screenshot 
![image](https://github.com/user-attachments/assets/49fa949e-be7e-4686-81f0-5027cd4c9ad1)

I have thrown the whole build log in a paste bin if its any help https://pastebin.com/kkC3xAFh

**Comment by steven-tey** [comment]
@Husky-Devel I believe this is because of Vercel's Edge Function size limit: https://vercel.link/edge-function-size (separate issue)

Will look into optimizing that!

**Comment by dmytrotree** [comment]
I am still facing problems with the route api/analytics/dashboard, encountering the same error that @Husky-Devel mentioned. However, it does not cause the build to fail, @steven-tey.
