### ISSUE TITLE
Add logo support to QR API

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#1301]
I've started adding this via #1279 but am currently blocked by https://github.com/vercel/satori/issues/592 (though I do think there should be a workaround)

If you can figure out the bug and get this working, you'd win 750 points since this is one of the long-standing bugs that we've been facing 😅

**Comment by RajuGangitla** [comment]
@steven-tey can i get more details about this issue ?

**Comment by steven-tey** [comment]
@RajuGangitla feel free to piggyback off the PR that I started – we basically want to add the ability to pass a custom logo to our QR code API. Currently it doesn't work for some reason, as detailed in https://github.com/vercel/satori/issues/592. Would love for you to figure it out!

**Comment by CntrlX** [comment]
can i work on it?

**Comment by unrenamed** [comment]
@steven-tey Have you considered converting the SVG to a PNG or JPG file before passing it to `ImageResponse`? I mean if SVG is not a strict requirement for the return type, then this may be a viable option.

**Comment by saiyalamarty** [comment]
Tried a workaround on mobile, and img tag with src seems to work instead of image and href. Away on vacation and laptop, so can't submit a PR. Someone else can verify and implement.

https://og-playground.vercel.app/?share=dVPtbpswFH0V5GniTxQbSNiCQqWt3bTPP2ulStMkRPDFODU2wyaQRnn32W3XQtMiIXHPObo-5_pyQIWigBK0pnz3R3oPjzZ7Aenh8IR4XgWcVSbx_ICQt_5sTPWcmupFhnLdiHxvuVLAMOUccsFbKAxX0ioKJbpaTjW54Ex-NVBrJwBpoJ0Ktp02vNyfK0tJ5-4l0SYvblirOknPlVCtVb0py_KZG9vhkt9C4kXhCXH9kD0mZMQdj_-_z57Atd6xk9mkbjT-6TRP8R2H_qMaUp94xLOkeyeCkguR-lJJmMBDLaRO_cqYJsG47_t5H81Vy3BICMHW00g9cmv98nri1_M4TX1e5wxIFmTh5JRX47weyC5TW9wb09aZiealKaicSzB42zBMQrxa4jDGixhHMck-Z-FqGcaL-N0yK0T__feg2Idq-HG50hdBHF2xm9vg-ucX_Tf49W1uG0wOw-OLcKkf6zW2C36GZkg1bt00Sg7oLgtK3ttLRff2UbJwBYVNx1BS5kLDDEGttvxq37jfxPR3le3j1uJTvQGKEtN2cJwhk2-sogIhVK9aQdHxHw

**Comment by steven-tey** [comment]
@saiyalamarty that looks really promising – anyone want to take this one up? Feel free to copy the implementation in my PR #1279 but adjust it to use @saiyalamarty's suggestion to see if it works 👀

**Comment by steven-tey** [comment]
@RajuGangitla are you still working on this?

**Comment by DeepaPrasanna** [comment]
May I have a try if no one's working?

**Comment by RajuGangitla** [comment]
@steven-tey let me try the @saiyalamarty solution and if i am not able to solve this issue by today night 
i will unassing myself

**Comment by RajuGangitla** [comment]
@BharathxD you can assign yourself now

**Comment by steven-tey** [comment]
This has been fixed 🤯  kudos to @BharathxD for the PR and @saiyalamarty for the pro-tip 🙏
