### ISSUE TITLE
Bug: Raycast Extension not showing all links (need pagination)

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#1597]
More details here: https://github.com/raycast/extensions/issues/14198

**Comment by DeepaPrasanna** [comment]
As this requires raycast running locally which only runs on macOS, I am unassigning myself. I dont have macOs.

**Comment by Ionfinisher** [comment]
Hey @steven-tey Hope you're doing well. As there was no draft PR for this issue within the 48h+ I've been working already on a solution for this issue. Tomorrow, I'll share my progress on this and ask for feedback if that's okay

**Comment by steven-tey** [comment]
@Ionfinisher sounds good!

**Comment by Ionfinisher** [comment]
Hey @steven-tey, sorry for the late response. Had a little more work today than I tought I would. Here is my update so far.

- Fist I refactored the `getAllShortLinks` function in the `api/index.ts` file for the use typeahead with the `search` param as mentioned in #14198 . As the dub API doesn't acctually provide a way to know if there's a next page when getting when the paginated response, I tryed coming up with a solution but not so efficient for the `hasMoreLinks`.

<img width="1099" alt="Screen Shot 2024-10-29 at 03 59 39" src="https://github.com/user-attachments/assets/cc211494-2e04-4da5-8bdc-47a48f548895">


- Updated the `useShortLinks` hook to dynamically accept a `query` parameter, so that different search queries can be passed as arguments.

<img width="814" alt="Screen Shot 2024-10-29 at 02 57 50" src="https://github.com/user-attachments/assets/cf605fd0-c6db-444f-8188-07707d3b404e">

- Updated the `List` to dynamically trigger typeahead when a page cursor is present for the next page of results. But if the number of links is < 100 then it uses keywords and use filtering=true

<img width="1099" alt="Screen Shot 2024-10-29 at 03 42 06" src="https://github.com/user-attachments/assets/400f9c71-2f78-42db-ab4c-c2284b17f641">

**Comment by steven-tey** [comment]
@Ionfinisher great work! can you link to the PR?

**Comment by Ionfinisher** [comment]
Hey @steven-tey here is the PR: [https://github.com/raycast/extensions/pull/15162](https://github.com/raycast/extensions/pull/15162)

**Comment by jfkisafk** [comment]
Hey @steven-tey , I am back and taking a look into this and will have an implementation along these lines: https://github.com/raycast/extensions/issues/14198#issuecomment-2311525240. For this I will need to call both these APIs in parallel for a search string:

* https://dub.co/docs/api-reference/endpoint/retrieve-a-list-of-links
* https://dub.co/docs/api-reference/endpoint/retrieve-number-of-links

It would have been more optimal if retrieving a list of links had a _nextToken_ based pagination or _hasNextPage (boolean)_ as a response. Then we wouldn't have needed a different api to figure out that info.

Other alternative is that we use `page` based Raycast native pagination: https://developers.raycast.com/api-reference/user-interface/list#pagination. But even though it will dynamically load all the links, the user will need to keep scrolling down for it to load the links. I think typeahead is a better option.

**Comment by devkiran** [comment]
This has been fixed via https://github.com/raycast/extensions/pull/15611

Thanks for your contribution @jfkisafk
