### ISSUE TITLE
Closing the toast message after creating a tag closes the edit modal

### ISSUE THREAD

**Issue by DeepaPrasanna** [dubinc/dub#1654]
I was trying to close the toast after creating the tag while editing the link. I'm not sure if this behavior is expected, but it doesn't seem ideal, as all the changes I made were undone, and I had to edit it again.

As I have exhausted my tags creation limit, I can't show the same message though
https://www.loom.com/share/40eddb7c7e114a12ab2bf3ef6d4b8d8c?sid=76c8bceb-3756-4e34-b4f6-32abada29b91

**Comment by unrenamed** [comment]
Oddly, swiping it down on mobile does not close the last opened modal 🤔

**Comment by steven-tey** [comment]
/award 150 yeah this looks like a bug

**Comment by unrenamed** [comment]
@steven-tey, there’s a potential fix for Radix UI Dialog components (see [link](https://github.com/radix-ui/primitives/issues/2690#issuecomment-1945449832)), but adapting it for Vaul's Drawer is challenging due to its structure — for instance, the close button is adjacent to, rather than inside, the drawer content. I could submit a PR for the Radix Dialog fix **if you want,** but a solution for Vaul’s Drawer may need input from its authors. There’s a[ similar open issue in their repo](https://github.com/emilkowalski/vaul/issues/482), though the suggested fix doesn’t fully address it.
