### ISSUE TITLE
Show Destination URL in Analytics Page

### ISSUE THREAD

**Issue by abass** [dubinc/dub#311]
Just realized, could you show the destination URL somewhere on the analytics page?
![image](https://github.com/steven-tey/dub/assets/5505994/133edb67-5a33-4f7e-b692-cec29d2fea3e)

Realizing like 4 times now I wanted to check the destination URL (have these individual pages bookmarked), and I have to go back to the all links list to see the destination of the URL that I'm literally on the analytics page for. Just a bit strange, the fact that you show the short link URL twice, instead of destination once and short link once for example.

**Comment by dhavalCode** [comment]
@abass I appreciate your perspective, and I'm enthusiastic about taking on this task. 
@steven-tey Would you kindly consider assigning this issue to me? I'm confident in my ability to contribute effectively. 
Thanks :)

**Comment by steven-tey** [comment]
@dhavalCode Just did! Thank you 🙏

**Comment by steven-tey** [comment]
This has been fixed with our latest Analytics dashboard update: https://dub.sh/EMYdfyw

Caveat: For individual links, the "Top links" section is kinda useless (e.g. when the link has no clicks). We'll be improving that soon to display the destination URL instead (e.g. when you update the destination URL, we can show which destination URLs have more clicks).

Closing this issue for now and opening a new one: https://github.com/dubinc/dub/issues/501
