### ISSUE TITLE
Fix lowres placeholder image

### ISSUE THREAD

**Issue by steven-tey** [dubinc/dub#537]
![CleanShot 2024-01-04 at 18 53 40](https://github.com/dubinc/dub/assets/28986134/621853b0-43a2-4d0f-ae08-8092856fd995)

h/t to Tim for the discovery: https://twitter.com/TEQQED/status/1742860967040393334

**Comment by unrenamed** [comment]
@steven-tey let me know if I've overlooked something. Based on the [OP's feedback](https://twitter.com/TEQQED/status/1742860967040393334), it seems they were surprised to see the placeholder image instead of their [website](https://teqqed.com) icon. It appears to be more about identifying the root cause of this problem rather than just addressing the low-resolution issue.

**Comment by steven-tey** [comment]
@unrenamed good point, I mentioned a temporary fix: https://twitter.com/steventey/status/1743390529138938336

The main issue here is the fallback image for the favicon service we're using here (https://www.google.com/s2/favicons?sz=64&domain_url=dub.co) has a low resolution – it'd be great if we can customize it.

**Comment by unrenamed** [comment]
@steven-tey What do you think if we replace the fallback image returned by Google with a dynamic avatar from [avatar.vercel.sh](https://avatar.vercel.sh)? Like this:

<img width="445" alt="image" src="https://github.com/dubinc/dub/assets/32395926/bd5f2b6c-2b16-4d26-8f30-8f92e1287066">

**Comment by steven-tey** [comment]
@unrenamed yes that would work – we'll need to detect when the Google favicon service returns the fallback image and render the dynamic avatar
