### ISSUE TITLE
CRITICAL -- after adding a domain on dub, my vercel websites stopped working 

### ISSUE THREAD

**Issue by ferreiro** [dubinc/dub#810]
hey, earlier today I was trying to add domains to dub and added the root domain zootools.co. but then deleted to just keep it to the current setup of go.zootools.co

after this, none of my production websites are working, failing both the forms, the dashboard and the public websites:

- https://zootools.co/
- https://app.zootools.co/
- form.zootools (all. our public facing forms are down right now)

<img width="1255" alt="Screenshot 2024-04-23 at 6 55 49 PM" src="https://github.com/dubinc/dub/assets/7242959/cd987060-f80c-44c6-bc02-a74407dc5e76">

and after that, all the vercel domains are failing to be verified, even thought it has the right records:
<img width="1905" alt="Screenshot 2024-04-23 at 6 56 27 PM" src="https://github.com/dubinc/dub/assets/7242959/46d1714b-c1ae-43dc-82fe-9e7bdb077192">

the website has being down for around an hour or so. please let me know how we can navigate this critical bug.

**Comment by steven-tey** [comment]
Hey Jorge! So sorry about the confusion here! A few initial observations + thoughts:

- Looks like [zootools.co](http://zootools.co/) + [app.zootools.co](http://app.zootools.co/) are working again now, lmk if there's anything that's still broken

- For adding a `go.[domain.com]` subdomain, you should be adding a CNAME record on `go` that points to [cname.dub.co](http://cname.dub.co/): [dub.co/help/article/how-to-add-custom-domain#adding-a-subdomain](http://dub.co/help/article/how-to-add-custom-domain#adding-a-subdomain)

- Also, since you're using Cloudflare you will also need to follow this step: [dub.co/help/article/using-cloudflare-domains](http://dub.co/help/article/using-cloudflare-domains) (but you should already have it set up if you are using Vercel)

Regardless, we will be doing a full post-mortem on this to make sure this doesn't happen again in the future!

**Comment by ferreiro** [comment]
Thx @steven-tey! It turned out to be that the domain provider didn't auto-renew, it failed, and remove all the cloudflare DNS settings pointing to vercel... it was unfortunate cause it was at the same time as I was playing with domains setup on Dub.

https://twitter.com/JGFerreiro/status/1783183463795077614
